In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


### <i>NUMPY</i>

In [2]:

a2=np.array([1,2,3])
a2


array([1, 2, 3])

In [3]:
a3=np.array([
        [
            [1,2,3],[4,5,6],[7,8,9]
        ],
        [
            [10,11,12],[13,14,15],[16,17,18.2]
        ]
    ]
) 

In [4]:
#shape 
print(a2.shape)
print(a3.shape)

#number of dimensions
print(a2.ndim)
print(a3.ndim)

#data type of array
print(a2.dtype)
print(a3.dtype)

(3,)
(2, 3, 3)
1
3
int32
float64


#### <mark>IMP:</mark> Create a dataframe with the help of numpy 

In [5]:
#creating 
a2=a3[0]
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0

#### 1. Creating arrays

In [6]:
#with mannual entries
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [7]:
#ones 

ones=np.ones((3,3))
print(ones, end="\n\n")


#zeros

zeroes=np.zeros((3,3))
print(zeroes, end="\n\n")


#arrange : get from "start" to "stop" with certain "steps"

arangeArray=np.arange(0,50,2)
print(arangeArray,end="\n\n")


#with random integers
randomArr=np.random.randint(0,10,size=(6))
print(randomArr,end="\n\n")\


#with random fractions 
randArrFrac=np.random.random((3,4))
print(randArrFrac)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]

[5 0 3 2 0 8]

[[0.35416158 0.4327092  0.09106595 0.78144601]
 [0.17198016 0.6377597  0.00768692 0.56118563]
 [0.02126554 0.88312465 0.1512469  0.42626597]]


#### preudo random numbers:
<li style="margin:00px">to fixate the random number for every single  invocation of random function
</li>
<li style="margin:00px">we do this using <code>random.seed
</li></code>


In [8]:
np.random.seed(2) #fixing a seed for every execution

#compile this cell n times and get same 3X3 matrix
np.random.randint(1,10,size=(3,3))


array([[9, 9, 7],
       [3, 9, 8],
       [3, 2, 6]])

#### 2. viewing arrays and Matrices

In [9]:
# viewing all the unique numbers
print(np.unique(a2),end="\n\n")

#sliced values :

print(a3[:2,:2,:2],end="\n\n")



[1. 2. 3. 4. 5. 6. 7. 8. 9.]

[[[ 1.  2.]
  [ 4.  5.]]

 [[10. 11.]
  [13. 14.]]]



##### an excercise:

suppose we got this array

In [10]:
np.random.seed(1)
ar= np.random.randint(1,10,size=(2,2,2,3))
ar

#and we want to access the first 6,9,6 out of this then

array([[[[6, 9, 6],
         [1, 1, 2]],

        [[8, 7, 3],
         [5, 6, 3]]],


       [[[5, 3, 5],
         [8, 8, 2]],

        [[8, 1, 7],
         [8, 7, 2]]]])

In [11]:
#answer
ar[0][0][0][:]

array([6, 9, 6])

#### 3.manipulating the arrays 

##### Arithmetic

In [15]:
a1=np.array((1,2,3))
a1

array([1, 2, 3])

In [16]:
#addition
print(a1+1)  

#multiplication
print(a1*2)

#subtraction
print(a1-1)

#boolean comparison
print(a1>2)



[2 3 4]
[2 4 6]
[0 1 2]
[False False  True]


In [17]:
#between two arrays

p1=np.random.randint(0,10,size=(2,3))
p2=np.random.randint(0,10,size=(3))
print(p1, end="\n\n")
print(p2,end="\n\n")

#multiplying both of array
print(p1*p2)



[[0 1 8]
 [8 3 9]]

[8 7 3]

[[ 0  7 24]
 [64 21 27]]


### Broadcasting in simplest Terms :
<strong>
Get the highest order dimension of the 
matrix if and only if having highest order dimension count as 1 
to match with the other 
</strong>

#### numpy implementation of arithmetics

In [18]:
#add
print(np.add(p1,p2))

#multiply
print(np.multiply(p1,p2))

#divide
print(np.divide(p1,p2))


[[ 8  8 11]
 [16 10 12]]
[[ 0  7 24]
 [64 21 27]]
[[0.         0.14285714 2.66666667]
 [1.         0.42857143 3.        ]]


#### 4. Aggregation 

In [19]:
listy_list=[1,2,3]

print("Using numpy wala sum",np.sum(listy_list))
print("Using python wala sum",sum(listy_list))



Using numpy wala sum 6
Using python wala sum 6


<mark> Tip </mark>
 Remember to use python fuctions with python data structures and numpy function with numpy data structures
 
 

In [34]:
#summition 

massive_array=np.random.randint(1,10,100000)
%timeit sum(massive_array)
%timeit np.sum(massive_array)

#As we can see numpy sum funtion is optimized for working with numpy arrays

4.5 ms ± 46.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
17.5 µs ± 71.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [36]:
#max

np.max(massive_array)



9

In [37]:
#min
np.min(massive_array)

1

In [39]:
#count()
np.count_nonzero(massive_array)

100000

In [41]:
#standard deviation
np.std(massive_array)

2.5813748153842364

In [42]:
#meann
np.mean(massive_array)

5.00375

In [43]:
#median
np.median(massive_array)

5.0

In [44]:
#variance
np.var(massive_array)

6.6634959375

#### Relation between Variance and Standard Deviation

 = $$Standard Deviation=\sqrt{Variance}$$



Variance
σ2	=	 
2062 + 762 + (−224)2 + 362 + (−94)2
5
 
 	=	 
42436 + 5776 + 50176 + 1296 + 8836
5
 
 	=	 
108520
5
 
 	=	21704

#### Both  Variance and Standard Deviation are used to account the degree of distribution of data away from the mean of the data

![](https://www.mathsisfun.com/data/images/statistics-dogs-mean.gif)

![](https://www.mathsisfun.com/data/images/statistics-dogs-deviation.gif)

Varianc = 2062 + 762 + (−224)2 + 362 + (−94)2
/5
 
 	=	 
42436 + 5776 + 50176 + 1296 + 8836 /5
 
 	=	 
108520/5
 
 	=	21704 IS THE VARIANCE

Standard Deviation
σ	=	√21704
 	=	147.32...
 	=	147 (to the nearest mm)

#### 5. Reshaping and trasposing

In [54]:
a2=a2.reshape(9,1)  #Reshaping 

In [61]:
print(a2.T.shape)  #Transposing

(1, 9)


In [63]:
a2.T

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [82]:
salesData=np.random.randint(1,20,size=(5,3))
sales=pd.DataFrame(data=salesData,columns=["Almond Butter","Peanut Butter","Cashew Butter"],index=["Mon","Tues","Wed","Thrus", "Fri"])
sales.shape

(5, 3)

In [80]:
butterPricesData=np.array([10,8,12])
butterPrices=pd.DataFrame(butterPricesData,columns=["Prices"],index=["Almond Butter","Peanut Butter","Cashew Butter"])
butterPrices.shape

(3, 1)

In [83]:
sales["Total $"]=salesData.dot(butterPricesData)

In [84]:
sales

Almond Butter  Peanut Butter  Cashew Butter  Total $
Mon               19             19              5      402
Tues              10             15             17      424
Wed                1             11              7      182
Thrus             19             14              8      398
Fri                1              8             17      278

## Turning Images to Numpy Arrays

<img src="./amogus.jpg"></img>

In [89]:
from matplotlib.image import imread

panda=imread("./amogus.jpg")
panda.ndim, panda.size,panda.shape

(3, 3397986, (933, 1214, 3))